version: '2'

services:
  mariadb-master:
    image: 'docker.io/bitnami/mariadb:10.4-debian-10'
    ports:
      - '3308:3306'
    volumes:
      - './master:/bitnami/mariadb'
      - './conf/master.cnf:/opt/bitnami/mariadb/conf/my.cnf'
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=hi
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=212224
  mariadb-slave:
    image: 'docker.io/bitnami/mariadb:10.4-debian-10'
    ports:
      - '3309:3306'
    volumes:
      - './slave:/bitnami/mariadb'
      - './conf/slave.cnf:/opt/bitnami/mariadb/conf/my.cnf'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=hi
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=212224
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mariadb_master_data:
    driver: local
